name: Build and Deploy Hugo Site

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: recursive  # For git submodule themes
        fetch-depth: 0

    # For Hugo Modules (Go modules)
    - uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        cache: false
    
    # For NPM dependencies (if using PostCSS, Tailwind, etc.)
    - uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install NPM dependencies
      run: |
        if [ -f package.json ]; then
          npm ci
        fi

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2
      with:
        hugo-version: 'latest'
        extended: true

    # Initialize Hugo modules if needed
    - name: Initialize Hugo Modules
      run: |
        if [ -f go.mod ]; then
          hugo mod get -u
          hugo mod tidy
        fi

    - name: Build
      run: hugo --minify

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public
